In [ ]:
#Assignment 1 LAb Questions

In [17]:
#Q1
import numpy as np

#(a)
arr = np.arange(1, 21)

#(b) 
def is_prime(n):
    if n < 2: return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0: return False
    return True

primes = np.array([x for x in arr if is_prime(x)])

#(c)
mean_primes = primes.mean()
var_primes = primes.var(ddof=0) 
print("Primes:", primes)
print("Mean:", mean_primes)
print("Variance:", var_primes)

Primes: [ 2  3  5  7 11 13 17 19]
Mean: 9.625
Variance: 35.734375


In [18]:
#Q2
import numpy as np

#(a)
A = np.arange(1,17).reshape(4,4)

#(b) 
sub = A[2:4, 0:2]

#(c) 
det_sub = np.linalg.det(sub)
print("A=\n", A)
print("Sub=\n", sub)
print("Determinant of sub:", det_sub)

A=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sub=
 [[ 9 10]
 [13 14]]
Determinant of sub: -4.000000000000009


In [19]:
#Q3
import pandas as pd

#(a)
df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D', 'E'],
    'Math': [78, 85, 62, 90, 74],
    'Science': [82, 79, 88, 91, 70],
    'English': [75, 88, 65, 85, 80]
})

#(b)
df['Total'] = df[['Math','Science','English']].sum(axis=1)
df['Average'] = df['Total'] / 3

#(c)
top_idx = df['Average'].idxmax()
topper = df.loc[top_idx, ['Name','Average']]
print(df)
print("Topper:", topper['Name'], "with average", topper['Average'])


  Name  Math  Science  English  Total    Average
0    A    78       82       75    235  78.333333
1    B    85       79       88    252  84.000000
2    C    62       88       65    215  71.666667
3    D    90       91       85    266  88.666667
4    E    74       70       80    224  74.666667
Topper: D with average 88.66666666666667


In [20]:
#Q4
import numpy as np

#(a)
n = 1000
tosses = np.random.choice([0,1], size=n)  # 1=head, 0=tail

#(b)
heads = (tosses == 1).sum()
tails = (tosses == 0).sum()

#(c)
p_head = heads / n
print("Heads:", heads, "Tails:", tails)
print("Estimated P(head):", p_head, "Close to 0.5? ", abs(p_head - 0.5) < 0.05)

Heads: 504 Tails: 496
Estimated P(head): 0.504 Close to 0.5?  True


In [21]:
#Q5
import pandas as pd

#(a)
df = pd.DataFrame({
    'ID':[1,2,3,4,5],
    'Name':['A','B','C','D','E'],
    'Salary':[40000, 60000, 35000, 50000, 45000]
})

#(b)
df['Bonus'] = 0.10 * df['Salary']

#(c)
avg_salary = df['Salary'].mean()
above_avg = df[df['Salary'] > avg_salary]
print(df)
print("Above average salary:\n", above_avg)

   ID Name  Salary   Bonus
0   1    A   40000  4000.0
1   2    B   60000  6000.0
2   3    C   35000  3500.0
3   4    D   50000  5000.0
4   5    E   45000  4500.0
Above average salary:
    ID Name  Salary   Bonus
1   2    B   60000  6000.0
3   4    D   50000  5000.0


In [22]:
#Q6
import numpy as np

#(a)
A = np.arange(1,10).reshape(3,3)
A = np.array([[1,2,3],[0,1,4],[5,6,0]])

#(b)
At = A.T
Ainv = np.linalg.inv(A)

#(c)
identity_approx = A.dot(Ainv)
print("A:\n", A)
print("Transpose:\n", At)
print("Inverse:\n", Ainv)
print("A * Ainv ≈\n", identity_approx)

A:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Transpose:
 [[1 0 5]
 [2 1 6]
 [3 4 0]]
Inverse:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
A * Ainv ≈
 [[ 1.00000000e+00 -2.66453526e-15  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -7.10542736e-15  1.00000000e+00]]


In [23]:
#Q7
import numpy as np
np.random.seed(0)

#(a)
temps = np.random.uniform(20, 40, size=30)  

#(b)
hottest_idx = temps.argmax()
coldest_idx = temps.argmin()
hottest = temps[hottest_idx]
coldest = temps[coldest_idx]

#(c)
mean_t = temps.mean()
median_t = np.median(temps)
std_t = temps.std(ddof=0)

print("Hottest day index:", hottest_idx, "Temp:", hottest)
print("Coldest day index:", coldest_idx, "Temp:", coldest)
print("Mean:", mean_t, "Median:", median_t, "Std:", std_t)

Hottest day index: 20 Temp: 39.57236684465528
Coldest day index: 16 Temp: 20.404367948806513
Mean: 31.622406565891012 Median: 31.708079371655764 Std: 5.603480008456117


In [24]:
#Q8
import pandas as pd

#(a)
s = pd.Series([55, 32, 48, 39, 90, 61, 28, 73])

#(b) 
s_replaced = s.astype(object)
s_replaced[s_replaced < 40] = 'Fail'

#(c) 
passed = (s >= 40).sum()

print(s_replaced)
print("Number passed:", passed)

0      55
1    Fail
2      48
3    Fail
4      90
5      61
6    Fail
7      73
dtype: object
Number passed: 5


In [25]:
#Q9
import numpy as np
from collections import Counter

#(a)
rolls = np.random.randint(1,7, size=500)

#(b)
counts = Counter(rolls)

#(c)
relative_freq = {face: counts[face]/500 for face in range(1,7)}

print("Counts:", counts)
print("Relative frequencies:", relative_freq)

Counts: Counter({np.int32(4): 104, np.int32(1): 91, np.int32(5): 78, np.int32(6): 78, np.int32(2): 76, np.int32(3): 73})
Relative frequencies: {1: 0.182, 2: 0.152, 3: 0.146, 4: 0.208, 5: 0.156, 6: 0.156}


In [26]:
#Q10
import pandas as pd

#(a)
df = pd.DataFrame({
    'Name':['P1','P2','P3','P4','P5','P6'],
    'Quantity':[10,5,20,7,12,3],
    'Price':[100,200,40,150,80,500]
})

#(b)
df['Total'] = df['Quantity'] * df['Price']

#(c)
best = df.loc[df['Total'].idxmax()]

print(df)
print("Max revenue product:", best['Name'], "Revenue:", best['Total'])

  Name  Quantity  Price  Total
0   P1        10    100   1000
1   P2         5    200   1000
2   P3        20     40    800
3   P4         7    150   1050
4   P5        12     80    960
5   P6         3    500   1500
Max revenue product: P6 Revenue: 1500


In [27]:
#Q11
import pandas as pd
import numpy as np

#(a)
df = pd.DataFrame({
    'A':[1, np.nan, 3, np.nan],
    'B':[5, 6, np.nan, np.nan],
    'C':[9, 10, 11, 12]
})

#(b)
df_filled = df.fillna(df.mean())

#(c)
df_dropped = df[df.isna().sum(axis=1) <= 1]

print("Original:\n", df)
print("Filled:\n", df_filled)
print("Dropped (>1 missing removed):\n", df_dropped)

Original:
      A    B   C
0  1.0  5.0   9
1  NaN  6.0  10
2  3.0  NaN  11
3  NaN  NaN  12
Filled:
      A    B   C
0  1.0  5.0   9
1  2.0  6.0  10
2  3.0  5.5  11
3  2.0  5.5  12
Dropped (>1 missing removed):
      A    B   C
0  1.0  5.0   9
1  NaN  6.0  10
2  3.0  NaN  11


In [28]:
#Q12
import numpy as np
#(a)
arr = np.arange(1,31)

#(b)
mat = arr.reshape(5,6)

#(c)
evens = mat[mat % 2 == 0]
avg_evens = evens.mean()

print("Matrix:\n", mat)
print("Evens:", evens)
print("Average of evens:", avg_evens)

Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Evens: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
Average of evens: 16.0


In [29]:
#Q13
import pandas as pd

#(a)
df = pd.DataFrame({
    'Name':['A','B','C','D','E','F'],
    'Age':[19,21,18,22,20,17],
    'Marks':[65,72,55,81,68,93]
})

#(b)
overall_avg = df['Marks'].mean()
above_avg = df[df['Marks'] > overall_avg]

#(c)
young_high = df[(df['Age'] < 20) & (df['Marks'] > 60)]

print("Above overall average:\n", above_avg)
print("Names <20 and marks>60:\n", young_high['Name'].tolist())

Above overall average:
   Name  Age  Marks
3    D   22     81
5    F   17     93
Names <20 and marks>60:
 ['A', 'F']


In [31]:
#Q14
import pandas as pd

#(a)
df = pd.DataFrame({
    'Name':['A','B','C','D','E'],
    'Tasks_Completed':[50, 80, 20, 60, 45],
    'Hours_Worked':[40, 35, 20, 50, 30]
})

#(b)
df['Efficiency'] = df['Tasks_Completed'] / df['Hours_Worked']

#(c)
best = df.loc[df['Efficiency'].idxmax()]

print(df)
print("Most efficient:", best['Name'], "Efficiency:", best['Efficiency'])

  Name  Tasks_Completed  Hours_Worked  Efficiency
0    A               50            40    1.250000
1    B               80            35    2.285714
2    C               20            20    1.000000
3    D               60            50    1.200000
4    E               45            30    1.500000
Most efficient: B Efficiency: 2.2857142857142856
