In [1]:
print("Hello World!")

Hello World!


In [2]:
age = 25
print("Integer: ",age, type(age))

Integer:  25 <class 'int'>


In [8]:
height = 5.9
print("Float:", height, type(height))

Float: 5.9 <class 'float'>


In [10]:
is_student = True
print("Boolean: ", is_student, type(is_student))

Boolean:  True <class 'bool'>


In [13]:
#Arithmetic Operations
a = 10
b = 3
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Exponentiation:", a**b)

Addition: 13
Subtraction: 7
Multiplication: 30
Division: 3.3333333333333335
Floor Division: 3
Modulus: 1
Exponentiation: 1000


In [15]:
#Comparision Operations
x = 5
y = 8
print("Equal:", x==y)
print("Not Equal:", x!=y)
print("Greater than:", x>y)
print("Less than:", x<y)
print("Greater than or equal:", x>=y)
print("Less than or equal:", x<=y)

Equal: False
Not Equal: True
Greater than: False
Less than: True
Greater than or equal: False
Less than or equal: True


In [17]:
#Logical Operations
p = True
q = False
print("AND:", p and q)
print("OR:", p or q)
print("NOT p:", not p)
print("NOT q:", not q)

AND: False
OR: True
NOT p: False
NOT q: True


In [19]:
#String Operations
str1 = "Hello"
str2 = "World"
print("Concatenation:", str1+" "+str2)
print("Repetition:", str1*3)
print("Length:", len(str1))
print("Uppercase:", str1.upper())
print("Lowercase:", str1.lower())
print("Contains 'ell':", "ell" in str1)

Concatenation: Hello World
Repetition: HelloHelloHello
Length: 5
Uppercase: HELLO
Lowercase: hello
Contains 'ell': True


In [21]:
#For Loop
print("For loop - numbers 1 to 5:")
for i in range(1,6):
    print(i)
print("For loop - list items:")
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

For loop - numbers 1 to 5:
1
2
3
4
5
For loop - list items:
apple
banana
cherry


In [27]:
for i in range(1,6):
    for j in range(1,6):
        print(j, end=" ")
    print()

1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 


In [1]:
#While Loop
print("While Loop - countdown:")
count = 5
while count>0:
    print(count)
    count -= 1


While Loop - countdown:
5
4
3
2
1


In [3]:
#Find the sum of first 15 natural numbers;
sum = 0
i = 1 
while(i<=15):
    sum += i
    i += 1
print("Sum of first 15 natural numbers",sum)

Sum of first 15 natural numbers 120


In [6]:
#Find 15! using for loop
fact = 1
n = int(input("Enter the number:"))
for i in range(1,n+1):
    fact *= i
print("Factorial of 15 is:",fact)

Enter the number:15
Factorial of 15 is: 1307674368000


In [8]:
#Loop Control Statements
numbers = [1,2,3,4,5]
fruits = ["apple","banana","cherry"]
mixed = [1,"hello",3.14,True]
print(numbers)
print(fruits)
print(mixed)

[1, 2, 3, 4, 5]
['apple', 'banana', 'cherry']
[1, 'hello', 3.14, True]


In [12]:
#Check if number is divisible by 3 or not
n = 10
if n%3==0:
    print(n,"is divisible by 3")
else:
    print(n,"is not divisible by 3")

10 is not divisible by 3


In [15]:
#List Operations
my_list = [1,2,3,4]
my_list.append(5)
print(my_list)

[1, 2, 3, 4, 5]


In [17]:
#List operations
li = [1,2,4]
li.insert(2,3)
print(li)

[1, 2, 3, 4]


In [19]:
li.extend([5,6])
print(li)

[1, 2, 3, 4, 5, 6, 5, 6]


In [22]:
li.remove(6)
print(li)

[1, 2, 3, 4, 5]


In [25]:
print(li[2])

3


In [2]:
#List Slicing
num = [1,2,3,4,5,6,7,8,9]
print("Original:",num)
print("First 3:",num[:3])
print("Last 3:",num[-3:])
print("Middle:",num[3:7])
print("Every second:",num[::2])
print("Reverse:",num[::-1])
print("Length:",len(num))
print("Sum:",sum(num))
print("Max:",max(num))
print("Min:",min(num))

Original: [1, 2, 3, 4, 5, 6, 7, 8, 9]
First 3: [1, 2, 3]
Last 3: [7, 8, 9]
Middle: [4, 5, 6, 7]
Every second: [1, 3, 5, 7, 9]
Reverse: [9, 8, 7, 6, 5, 4, 3, 2, 1]
Length: 9
Sum: 45
Max: 9
Min: 1


In [4]:
squares = [x**2 for x in range(1,6)]
print("Squares:", squares)

Squares: [1, 4, 9, 16, 25]


In [7]:
even_squares= [x**2 for x in range(1,11) if x%2==0]
print("Even Squares:",even_squares)

Even Squares: [4, 16, 36, 64, 100]


In [3]:
matrix = [[i*j for j in range(1,4)] for i in range (1,4)]
print("Matrix:", matrix)

Matrix: [[1, 2, 3], [2, 4, 6], [3, 6, 9]]


In [6]:
#Creating Tuples
simple_tuple = (1,2,3)
mixed_tuple = (1,"hello",3.14,True)
single_tuple = (42,) #Note the comma
empty_tuple = ()
print(simple_tuple)
print(mixed_tuple)
print(single_tuple)
print(empty_tuple)

(1, 2, 3)
(1, 'hello', 3.14, True)
(42,)
()


In [9]:
#Creating Dictonaries
student={
    "name": "Alice",
    "age": 20,
    "courses":["Math","Science"],
    "gpa":3.8
}

empty_dict = {}
another_dict = dict(name="Bob", age=22)

print("Student:",student)
print("Empty",empty_dict)
print("Another:",another_dict)

Student: {'name': 'Alice', 'age': 20, 'courses': ['Math', 'Science'], 'gpa': 3.8}
Empty {}
Another: {'name': 'Bob', 'age': 22}


In [12]:
om={
    "name": "Om Singh",
    "Roll": 63,
    "Age": 21,
    "Reg No": 2341019519,
    "Course": "Machine Learning Concepts 1",
    "Section": "G3"
}

print(om)

{'name': 'Om Singh', 'Roll': 63, 'Age': 21, 'Reg No': 2341019519, 'Course': 'Machine Learning Concepts 1', 'Section': 'G3'}


In [1]:
#Dictionaries Operations

#Accessing Values
print(om["name"])
print(om.get("age"))
print("Country:",om.get("country","Not specified"))

#Adding/Updating
om["email"] = "ninjaplays792020@gmail.com"
om["age"] = 22
print(om)

#Removing
removed = om.pop("Section")
print(removed)
print(om)

NameError: name 'om' is not defined

In [7]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5])
print(arr)
mat = np.array([[1,2,3],[4,5,6]])
print(mat)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [19]:
#Special Arrays
zeros = np.zeros((2,3))
ones = np.ones((2,3))
arange = np.arange(0,10,2)
linspace = np.linspace(0,1,10)
identity = np.eye(3)
print(zeros)
print(ones)
print(arange)
print(linspace)
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

NameError: name 'arr' is not defined

In [5]:
import numpy as np

In [8]:
a = np.array([10,20,30,40,50])
print(a[0]) #first element
print(a[-1]) #last element
print(a[1:4]) #slicing

b = np.array([[1,2,3],[4,5,6]])
print(b[0,2]) #row 0, col 2
print(b[:,1]) #all rows, col 1

10
50
[20 30 40]
3
[2 5]


In [13]:
#Create one two dimensional array of dimension 3*3
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(v[1][0])
print(v[:,2])
print(v[1,:])

4
[3 6 9]
[4 5 6]


In [15]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y) #element-wise addition
print(x*y) #element-wise multiplication
print(x**2) #square

print(np.sqrt(x)) #square root
print(np.exp(x)) #exponential
print(np.sin(x)) #sine

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]


In [17]:
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
print(A@B) #matrix multiplication
print(np.dot(A,B)) #dot product
print(A.T) #transpose

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [19]:
nums = np.array([1,2,3,4,5])
print(nums.sum())
print(nums.mean())
print(nums.max())
print(nums.min())
print(nums.std())

15
3.0
5
1
1.4142135623730951


In [23]:
arr = np.arange(1,13)
reshaped = arr.reshape(3,4)
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [26]:
print(np.random.rand(3)) # 3 random numbers
print(np.random.randint(1,10,5))
print(np.random.randn(2,3))

[0.98336637 0.41809008 0.8337897 ]
[2 1 2 7 3]
[[-0.31480841  0.62707627  0.43304642]
 [ 1.33465706 -0.06869753 -0.75899243]]


In [28]:
#Create an array of integers
arr = np.array([1,2,3,4,5])
print("Original array:",print(s[])arr)
print("Data type:",arr.dtype)

Original array: [1 2 3 4 5]
Data type: int64


In [30]:
#Q1
marks = int(input())
if marks>=90 and marks<=100:
    print("Grade A")
elif marks>=75 and marks<=89:
    print("Grade B")
elif marks>=50 and marks<=74:
    print("Grade C")
else:
    print("Fail")

57
Grade C


In [32]:
#Q2
x = int(input())
sum =0
while x>0:
    d = x%10
    sum +=d
    x //= 10
print(sum)

1234
10


In [41]:
#Q3
def isPrime(n):
    count =0
    
    for i in range(1,n+1):
        if n%i==0:
            count +=1
            
    if count==2:
        print("Prime")
    else:
        print("Not Prime")
     
isPrime(int(input()))

78
Not Prime


In [47]:
#Q4
s = "abcba"
srev = s[::-1]
if s==srev:
    print("Palindrome")
else:
    print("Not Palindrome")

Palindrome


In [57]:
#Q5
x = np.array([[56,73,34],[42,58,61],[78,81,93]])
y = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(x@y)
print(np.linalg.det(x))
xinv = np.linalg.inv(x)
print(xinv)
print(x@xinv)

[[2053 2216 2379]
 [2150 2311 2472]
 [3321 3573 3825]]
49415.99999999997
[[ 0.00916707 -0.08165372  0.05020641]
 [ 0.01724138  0.05172414 -0.04022989]
 [-0.0227052   0.02343371  0.00368302]]
[[ 1.00000000e+00  6.93889390e-18 -2.90566182e-16]
 [-4.51028104e-17  1.00000000e+00 -1.81712284e-16]
 [ 6.59194921e-17 -3.98986399e-16  1.00000000e+00]]


In [59]:
marks=[]
for i in range(10):
    score = int(input())
    marks.append(score)

marks2 = np.array(marks)
average = np.mean(marks2)

for i in marks2:
    if i>average:
        print(i)

1
2
3
4
5
6
7
8
9
10
6
7
8
9
10
