In [9]:
li = [1,2,3,4,5,6,6,6,7,8]
li.remove(6)
li

[1, 2, 3, 4, 5, 6, 6, 7, 8]

In [17]:
matrix = [[i*j for j in range(1,4)] for i in range (1,4)]
print("Matrix:", matrix)

Matrix: [[1, 2, 3], [2, 4, 6], [3, 6, 9]]


In [29]:
student={
    "name": "Alice",
    "age": 20,
    "courses": ["Math","Science"],
    "gpa": 3.8
}

empty_dict = {}
another_dict = dict(name="Bob", age=22)

print("Student:",student)
print("Empty",empty_dict)
print("Another:",another_dict)
type(student)

Student: {'name': 'Alice', 'age': 20, 'courses': ['Math', 'Science'], 'gpa': 3.8}
Empty {}
Another: {'name': 'Bob', 'age': 22}


dict

In [3]:
import numpy as np
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
mat= np.array([[1,2,3],[4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
arange = np.arange(0,10,2)
arange

array([0, 2, 4, 6, 8])

In [7]:
linspace = np.linspace(0,1,5)
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
identity = np.eye(3)
type(identity[0][1])

numpy.float64

In [9]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [13]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(4,)
1
4
int64


In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a[0])
print(a[-1])
print(a[1:4])

1
5
[2 3 4]


In [4]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(v[:,1])

[2 5 8]


In [9]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y) #element-wise addition
print(x*y) #element-wise multiplication
print(x**2) #square
print(np.sqrt(x)) #square root
print(np.exp(x)) #exponential
print(np.sin(x)) #sine

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]


In [4]:
arr = np.arange(1,13)
arr
reshape=arr.reshape(3,4)
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
import pandas as pd

In [6]:
S=pd.Series()
print(S)

Series([], dtype: object)


In [7]:
S=pd.Series([1,2,3])
print(S)

0    1
1    2
2    3
dtype: int64


In [10]:
S=pd.Series([1,2,3], index=['a','b','c'])
print(S)

a    1
b    2
c    3
dtype: int64


In [11]:
[S>2]

[a    False
 b    False
 c     True
 dtype: bool]

In [12]:
a=np.array([1,2,3])
a*2

array([2, 4, 6])

In [13]:
li=[1,2,3]
li*2

[1, 2, 3, 1, 2, 3]

In [14]:
data={
    'Name':['Guru','Rajendra','Om','Sourav','Sai'],
    'Age':[21,21,21,None,None],
    'City':['Cuttack','Angul','Jamshedpur','Balasore','BBSR'],
    'Marks':[91,96,92,94,97]
}
df = pd.DataFrame(data)
print(df)

       Name   Age        City  Marks
0      Guru  21.0     Cuttack     91
1  Rajendra  21.0       Angul     96
2        Om  21.0  Jamshedpur     92
3    Sourav   NaN    Balasore     94
4       Sai   NaN        BBSR     97


In [15]:
df.shape

(5, 4)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    5 non-null      object 
 1   Age     3 non-null      float64
 2   City    5 non-null      object 
 3   Marks   5 non-null      int64  
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes


In [17]:
df.describe()

Age     Marks
count   3.0   5.00000
mean   21.0  94.00000
std     0.0   2.54951
min    21.0  91.00000
25%    21.0  92.00000
50%    21.0  94.00000
75%    21.0  96.00000
max    21.0  97.00000

In [24]:
print(df.iloc[3:])

     Name  Age      City  Marks
3  Sourav  NaN  Balasore     94
4     Sai  NaN      BBSR     97


In [25]:
print(df.loc[0,'Name'])

Guru


In [26]:
print(df.loc[2,'City'])

Jamshedpur


In [28]:
import pandas as pd
import numpy as np

df = pd.Series((8,9,10,11),index=('a','b','c','d'))
print(df)

a     8
b     9
c    10
d    11
dtype: int64


In [30]:
s = pd.Series([1,2,3,4])
df = pd.DataFrame(s,columns=["num"])
print(df)

   num
0    1
1    2
2    3
3    4


In [31]:
dicl=[
    {'FirstName': 'Sachin','LastName':'Bhardwaj','Age':21},
    {'FirstName': 'Vinod','LastName':'Verma','Age':23},
    {'FirstName': 'Rajesh','LastName':'Mishra','Age':22},
]
df1 = pd.DataFrame(dicl)
print(df1,"\n")

  FirstName  LastName  Age
0    Sachin  Bhardwaj   21
1     Vinod     Verma   23
2    Rajesh    Mishra   22 



In [33]:
for(ri,rv) in df1.iterrows():
    print(ri,"\n")
    print(rv,"\n")

0 

FirstName      Sachin
LastName     Bhardwaj
Age                21
Name: 0, dtype: object 

1 

FirstName    Vinod
LastName     Verma
Age             23
Name: 1, dtype: object 

2 

FirstName    Rajesh
LastName     Mishra
Age              22
Name: 2, dtype: object 



In [34]:
empdata = {
    'empid': [101,102,103,105,106],
    'ename': ['Sachin','Vinod','Lakhbir','Anil','Om']
}
df = pd.DataFrame(empdata)
print(df)

   empid    ename
0    101   Sachin
1    102    Vinod
2    103  Lakhbir
3    105     Anil
4    106       Om


In [35]:
df[['empid','ename']]

empid    ename
0    101   Sachin
1    102    Vinod
2    103  Lakhbir
3    105     Anil
4    106       Om

In [37]:
df.empid

0    101
1    102
2    103
3    105
4    106
Name: empid, dtype: int64